module.exports = [
  {
    name: "TenZ 准星",
    code: "0;s;1;P;c;5;h;0;m;1;0l;4;0o;2;0a;1;0f;0;1b;0;S;c;4;o;1",
    local_img: "valorant_assets\/TenZ_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/tenz.png",
  },
  {
    name: "yay 准星",
    code: "0;P;h;0;f;0;0l;4;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/yay_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/yay.png",
  },
  {
    name: "Sacy 准星",
    code: "0;P;h;0;f;0;0t;1;0l;4;0o;1;0a;1;0f;0;1t;3;1o;2;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Sacy_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/sacy.png",
  },
  {
    name: "f0rsakeN 准星",
    code: "0;P;o;1;f;0;0t;1;0l;1;0o;4;0a;1;0f;0;1t;1;1l;1;1o;3;1a;0;1m;0;1f;0",
    local_img: "valorant_assets\/f0rsakeN_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/f0rsaken.png",
  },
  {
    name: "ScreaM 准星",
    code: "0;P;c;5;o;0.286;d;1;f;0;0t;0;0l;0;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/ScreaM_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/scream.png",
  },
  {
    name: "Dep 准星",
    code: "0;s;1;P;o;0.1;f;0;s;0;0t;1;0l;2;0o;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Dep_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/dep.png",
  },
  {
    name: "LESS 准星",
    code: "0;P;o;0;f;0;0t;1;0l;2;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/LESS_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/less.png",
  },
  {
    name: "Aspas 准星",
    code: "0;P;c;5;o;1;d;1;z;3;f;0;0b;0;1b;0",
    local_img: "valorant_assets\/Aspas_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/aspas.png",
  },
  {
    name: "cNed 准星",
    code: "0;P;h;0;f;0;0l;5;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/cNed_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/cned.png",
  },
  {
    name: "zekken 准星",
    code: "0;P;h;0;f;0;0t;1;0l;3;0o;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/zekken_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/zekken.png",
  },
  {
    name: "Cryo 准星",
    code: "0;P;c;5;h;0;f;0;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Cryo_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/cryo.png",
  },
  {
    name: "Tarik 准星",
    code: "0;P;o;1;d;1;0b;0;1b;0",
    local_img: "valorant_assets\/Tarik_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/tarik.png",
  },
  {
    name: "Sinatraa 准星",
    code: "0;P;c;5;o;1;f;0;0t;1;0l;3;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Sinatraa_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/sinatraa.png",
  },
  {
    name: "BONECOLD 准星",
    code: "0;P;c;1;h;0;f;0;0l;2;0o;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/BONECOLD_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/bonecold.png",
  },
  {
    name: "Crow 准星",
    code: "0;s;1;P;o;1;f;0;0t;1;0l;1;0o;1;0a;1;0f;0;1b;0;S;c;0;s;0.5;o;1",
    local_img: "valorant_assets\/Crow_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/crow.png",
  },
  {
    name: "nAts 准星",
    code: "0;P;c;1;o;1;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/nAts_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/nats.png",
  },
  {
    name: "Koldamenta 准星",
    code: "0;P;c;7;h;0;f;0;0l;0;0o;4;0a;1;0f;0;1t;4;1o;1;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Koldamenta_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/koldamenta.png",
  },
  {
    name: "Derke 准星",
    code: "0;P;o;1;d;1;f;0;s;0;0t;0;0l;1;0o;0;0a;1;0f;0;1t;0;1l;1;1o;0;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Derke_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/derke.png",
  },
  {
    name: "Asuna 准星",
    code: "0;P;o;1;0t;1;0l;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Asuna_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/asuna.png",
  },
  {
    name: "Jamppi 准星",
    code: "0;s;1;P;h;0;0t;1;0o;2;0a;1;0f;0;1t;0;1l;0;1o;0;1a;0;1m;0;1f;0;S;o;0.502",
    local_img: "valorant_assets\/Jamppi_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/jamppi.png",
  },
  {
    name: "Lakia 准星",
    code: "0;P;h;0;0t;5;0l;1;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Lakia_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/lakia.png",
  },
  {
    name: "Tennn 准星",
    code: "0;P;h;0;0l;4;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Tennn_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/tennn.png",
  },
  {
    name: "Jinggg 准星",
    code: "0;s;1;P;c;1;o;1;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0;S;c;5",
    local_img: "valorant_assets\/Jinggg_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/jinggg.png",
  },
  {
    name: "Zombs 准星",
    code: "0;P;h;0;f;0;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Zombs_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/zombs.png",
  },
  {
    name: "Mahluna 准星",
    code: "0;c;1;P;c;5;o;0;m;1;0t;4;0l;2;0o;1;0a;1;0e;0;1b;0",
    local_img: "valorant_assets\/Mahluna_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/mahluna.png",
  },
  {
    name: "Shao 准星",
    code: "0;P;c;5;h;0;d;1;f;0;0l;4;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Shao_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/shao.png",
  },
  {
    name: "Ardiis 准星",
    code: "0;P;c;5;h;0;f;0;0t;1;0l;0;0o;0;0a;1;0f;0;1t;1;1o;1;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Ardiis_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/ardiis.png",
  },
  {
    name: "Soulcas 准星",
    code: "0;s;1;P;o;1;d;1;z;3;f;0;0b;0;1b;0;S;s;0.762",
    local_img: "valorant_assets\/Soulcas_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/soulcas.png",
  },
  {
    name: "BuZz 准星",
    code: "0;P;c;5;o;1;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/BuZz_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/buzz.png",
  },
  {
    name: "Nadeshot 准星",
    code: "0;P;h;0;f;0;0l;4;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Nadeshot_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/nadeshot.png",
  },
  {
    name: "JonahP 准星",
    code: "0;P;c;5;o;1;0t;1;0l;3;0o;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/JonahP_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/jonahp.png",
  },
  {
    name: "otom 准星",
    code: "0;P;c;5;h;0;f;0;0t;1;0o;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/otom_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/otom.png",
  },
  {
    name: "Sheydos 准星",
    code: "0;P;c;7;t;2;o;1;d;1;f;0;0b;0;1b;0",
    local_img: "valorant_assets\/Sheydos_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/sheydos.png",
  },
  {
    name: "Kyedae 准星",
    code: "0;P;c;5;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Kyedae_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/kyedae.png",
  },
  {
    name: "ShahZaM 准星",
    code: "0;P;c;1;o;1;f;0;0l;5;0a;0.5;0f;0;1b;0",
    local_img: "valorant_assets\/ShahZaM_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/shahzam.png",
  },
  {
    name: "ANGE1 准星",
    code: "0;P;c;7;h;0;f;0;0l;4;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/ANGE1_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/ange1.png",
  },
  {
    name: "Nivera 准星",
    code: "0;s;1;P;o;1;0t;1;0l;2;0o;2;0a;1;0f;0;1t;0;1l;0;1o;0;1a;0;S;c;1;o;0.5",
    local_img: "valorant_assets\/Nivera_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/nivera.png",
  },
  {
    name: "Wardell 准星",
    code: "0;P;c;5;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Wardell_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/wardell.png",
  },
  {
    name: "LuckeRRR 准星",
    code: "0;P;c;1;h;0;d;1;a;0.98;0b;0;1b;0",
    local_img: "valorant_assets\/LuckeRRR_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/luckerrr.png",
  },
  {
    name: "Cryocells 准星",
    code: "0;P;h;0;f;0;0l;4;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Cryocells_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/cryocells.png",
  },
  {
    name: "Dicey 准星",
    code: "0;P;c;5;h;0;f;0;0t;1;0l;3;0o;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Dicey_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/dicey.png",
  },
  {
    name: "Leaf 准星",
    code: "0;P;h;0;f;0;0l;4;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Leaf_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/leaf.png",
  },
  {
    name: "Marved 准星",
    code: "0;P;c;1;h;0;f;0;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Marved_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/marved.png",
  },
  {
    name: "Ninja 准星",
    code: "0;P;c;5;h;0;0l;7;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Ninja_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/ninja.png",
  },
  {
    name: "MaKo 准星",
    code: "0;P;c;1;o;1;f;0;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/MaKo_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/mako.png",
  },
  {
    name: "Laz 准星",
    code: "0;p;0;c;1;s;1;P;o;1;f;0;m;1;0t;1;0l;3;0a;1;0f;0;1b;0;A;c;7;o;0;d;1;z;3;m;1;0t;3;0l;2;0o;0;0a;0.5;0f;0;1b;0;S;d;0",
    local_img: "valorant_assets\/Laz_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/laz.png",
  },
  {
    name: "Patiphan 准星",
    code: "0;P;c;5;h;0;d;1;0t;6;0l;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Patiphan_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/patiphan.png",
  },
  {
    name: "Nukkye 准星",
    code: "0;s;1;P;o;1;d;1;f;0;0b;0;1b;0;S;s;0.85;o;1",
    local_img: "valorant_assets\/Nukkye_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/nukkye.png",
  },
  {
    name: "Sayaplayer 准星",
    code: "0;s;1;P;c;1;0t;1;0l;3;0o;1;0a;1;0f;0;1b;0;S;c;1;s;0.75;o;1",
    local_img: "valorant_assets\/Sayaplayer_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/sayaplayer.png",
  },
  {
    name: "Zeek 准星",
    code: "0;P;c;7;o;1;d;1;f;0;0b;0;1b;0",
    local_img: "valorant_assets\/Zeek_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/zeek.png",
  },
  {
    name: "Magnum 准星",
    code: "0;P;c;1;o;1;d;1;z;3;0t;0;0l;0;0o;0;0a;0;1t;0;1l;0;1a;0",
    local_img: "valorant_assets\/Magnum_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/magnum.png",
  },
  {
    name: "Benkai 准星",
    code: "0;P;c;5;o;1;d;1;f;0;0t;0;0l;0;0o;0;0a;0;0f;0;1b;0",
    local_img: "valorant_assets\/Benkai_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/benkai.png",
  },
  {
    name: "Mistic 准星",
    code: "0;P;o;1;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Mistic_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/mistic.png",
  },
  {
    name: "SugarZ3ro 准星",
    code: "0;P;c;1;o;1;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/SugarZ3ro_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/sugarz3ro.png",
  },
  {
    name: "Drone 准星",
    code: "0;P;c;1;o;1;0l;1;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Drone_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/drone.png",
  },
  {
    name: "Mixwell 准星",
    code: "0;P;h;0;f;0;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Mixwell_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/mixwell.png",
  },
  {
    name: "valyn 准星",
    code: "0;s;1;P;h;0;f;0;0l;5;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/valyn_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/valyn.png",
  },
  {
    name: "Subroza 准星",
    code: "0;P;c;7;o;0.715;f;0;0t;1;0l;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Subroza_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/subroza.png",
  },
  {
    name: "L1NK 准星",
    code: "0;s;1;P;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/L1NK_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/l1nk.png",
  },
  {
    name: "Aleko 准星",
    code: "0;P;h;0;0b;0;1t;1;1l;5;1o;2;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Aleko_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/aleko.png",
  },
  {
    name: "Zander 准星",
    code: "0;P;h;0;f;0;0l;5;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Zander_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/zander.png",
  },
  {
    name: "Redgar 准星",
    code: "0;P;c;1;h;0;f;0;0t;1;0l;4;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Redgar_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/redgar.png",
  },
  {
    name: "Corey 准星",
    code: "0;P;c;5;h;0;f;0;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Corey_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/corey.png",
  },
  {
    name: "Skadoodle 准星",
    code: "0;P;o;1;0t;1;0l;2;0o;2;0a;1;0f;0;1t;1;1l;0;1o;1;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Skadoodle_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/skadoodle.png",
  },
  {
    name: "Hoody 准星",
    code: "0;s;1;P;o;1;d;1;f;0;0b;0;1b;0;S;s;0.85;o;1",
    local_img: "valorant_assets\/Hoody_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/hoody.png",
  },
  {
    name: "Nitr0 准星",
    code: "0;P;t;2;o;1;0l;3;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Nitr0_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/nitr0.png",
  },
  {
    name: "keznit 准星",
    code: "0;P;c;4;h;0;0b;0;1l;4;1o;2;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/keznit_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/keznit.png",
  },
  {
    name: "Aimdll 准星",
    code: "0;P;c;1;o;1;0t;1;0l;4;0o;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Aimdll_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/aimdll.png",
  },
  {
    name: "paTiTek 准星",
    code: "0;P;o;1;d;1;0t;0;0l;0;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/paTiTek_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/patitek.png",
  },
  {
    name: "Klaus 准星",
    code: "0;P;c;1;o;1;0t;1;0l;3;0o;1;0a;1;0f;0;1t;0;1l;0;1a;0",
    local_img: "valorant_assets\/Klaus_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/klaus.png",
  },
  {
    name: "Saadhak 准星",
    code: "0;P;c;1;o;1;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Saadhak_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/saadhak.png",
  },
  {
    name: "Hazed 准星",
    code: "0;P;c;7;h;0;f;0;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Hazed_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/hazed.png",
  },
  {
    name: "NBK 准星",
    code: "0;P;h;0;0t;1;0l;1;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/NBK_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/nbk.png",
  },
  {
    name: "Mendo 准星",
    code: "0;P;c;5;o;1;d;1;0t;0;0l;0;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Mendo_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/mendo.png",
  },
  {
    name: "mindfreak 准星",
    code: "0;P;c;1;o;0.723;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/mindfreak_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/mindfreak.png",
  },
  {
    name: "Vanity 准星",
    code: "0;P;c;1;h;0;f;0;0t;3;0l;1;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Vanity_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/vanity.png",
  },
  {
    name: "trent 准星",
    code: "0;P;c;5;h;0;0l;4;0o;2;0a;1;0f;0;1a;0;1m;0;1f;0",
    local_img: "valorant_assets\/trent_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/trent.png",
  },
  {
    name: "Dizzy 准星",
    code: "0;P;c;1;o;1;0t;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Dizzy_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/dizzy.png",
  },
  {
    name: "PANcada 准星",
    code: "0;P;c;1;h;0;s;0;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/PANcada_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/pancada.png",
  },
  {
    name: "ShadoW 准星",
    code: "0;P;c;1;o;1;0l;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/ShadoW_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/shadow.png",
  },
  {
    name: "Rb 准星",
    code: "0;P;c;5;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Rb_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/rb.png",
  },
  {
    name: "d4v41 准星",
    code: "0;s;1;P;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/d4v41_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/d4v41.png",
  },
  {
    name: "NagZ 准星",
    code: "0;P;c;1;o;1;d;1;0l;0;0o;2;0a;1;0f;0;1t;0;1l;0;1o;0;1a;0",
    local_img: "valorant_assets\/NagZ_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/nagz.png",
  },
  {
    name: "Al0rante 准星",
    code: "0;P;c;7;h;0;d;1;z;1;f;0;0t;1;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Al0rante_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/al0rante.png",
  },
  {
    name: "Wippie 准星",
    code: "0;P;c;4;o;1;f;0;0t;1;0l;4;0o;0;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Wippie_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/wippie.png",
  },
  {
    name: "Rhyme 准星",
    code: "0;P;c;4;h;0;d;1;z;1;f;0;0l;5;0o;2;0a;1;0f;0;1t;3;1o;3;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Rhyme_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/rhyme.png",
  },
  {
    name: "Steel 准星",
    code: "0;P;c;4;h;0;f;0;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Steel_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/steel.png",
  },
  {
    name: "Ec1s 准星",
    code: "0;P;c;1;h;0;0l;5;0o;1;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Ec1s_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/ec1s.png",
  },
  {
    name: "Dimasick 准星",
    code: "0;P;c;1;h;0;d;1;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Dimasick_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/dimasick.png",
  },
  {
    name: "Chronicle 准星",
    code: "0;P;c;1;o;1;f;0;0t;1;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Chronicle_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/chronicle.png",
  },
  {
    name: "Floppy 准星",
    code: "0;P;c;4;t;2;o;1;d;1;0l;4;0o;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Floppy_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/floppy.png",
  },
  {
    name: "Ethan 准星",
    code: "0;P;o;1;0t;1;0l;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Ethan_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/ethan.png",
  },
  {
    name: "SicK 准星",
    code: "0;P;c;1;o;1;f;0;0l;3;0o;5;0a;1;0f;0;1t;0;1a;0.379",
    local_img: "valorant_assets\/SicK_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/sick.png",
  },
  {
    name: "Summit1g 准星",
    code: "0;P;o;1;0l;5;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Summit1g_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/summit1g.png",
  },
  {
    name: "D3ffo 准星",
    code: "0;P;o;1;d;1;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/D3ffo_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/d3ffo.png",
  },
  {
    name: "dapr 准星",
    code: "0;P;c;1;o;1;f;0;0l;3;0o;5;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/dapr_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/dapr.png",
  },
  {
    name: "Shanks 准星",
    code: "0;P;c;1;o;1;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Shanks_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/shanks.png",
  },
  {
    name: "Vice 准星",
    code: "0;P;c;5;h;0;f;0;0l;2;0o;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Vice_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/vice.png",
  },
  {
    name: "AvovA 准星",
    code: "0;p;0;s;1;P;c;5;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0;A;o;1;d;1;0b;0;1b;0",
    local_img: "valorant_assets\/AvovA_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/avova.png",
  },
  {
    name: "ZachaREEE 准星",
    code: "0;P;c;5;h;0;f;0;0t;1;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/ZachaREEE_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/zachareee.png",
  },
  {
    name: "Dephh 准星",
    code: "0;P;o;1;f;0;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Dephh_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/dephh.png",
  },
  {
    name: "Relyks 准星",
    code: "0;P;o;1;0t;1;0l;2;0a;1;0f;0;1t;0;1l;0;1o;5;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Relyks_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/relyks.png",
  },
  {
    name: "Xeppaa 准星",
    code: "0;P;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Xeppaa_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/xeppaa.png",
  },
  {
    name: "stax 准星",
    code: "0;P;c;4;h;0;f;0;s;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/stax_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/stax.png",
  },
  {
    name: "Nitro 准星",
    code: "0;P;h;0;d;1;f;0;0t;1;0l;3;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Nitro_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/nitro.png",
  },
  {
    name: "Victor 准星",
    code: "0;P;h;0;f;0;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Victor_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/victor.png",
  },
  {
    name: "Zest 准星",
    code: "0;P;c;1;o;1;f;0;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Zest_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/zest.png",
  },
  {
    name: "delz1k 准星",
    code: "0;P;c;1;o;0;f;0;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/delz1k_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/delz1k.png",
  },
  {
    name: "Seb 准星",
    code: "0;P;c;5;o;1;0t;1;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Seb_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/seb.png",
  },
  {
    name: "Horcus 准星",
    code: "0;P;c;1;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Horcus_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/horcus.png",
  },
  {
    name: "JASONR 准星",
    code: "0;P;c;1;o;1;d;1;0l;3;0o;5;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/JASONR_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/jasonr.png",
  },
  {
    name: "Meddo 准星",
    code: "0;P;c;1;h;0;0b;0;1l;3;1o;2;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Meddo_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/meddo.png",
  },
  {
    name: "N0thing 准星",
    code: "0;P;c;1;o;0.969;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/N0thing_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/n0thing.png",
  },
  {
    name: "Hiko 准星",
    code: "0;P;c;1;h;0;d;1;z;1;f;0;0t;1;0l;2;0a;1;0f;0;1l;5;1o;4;1a;1;1m;0;1f;0",
    local_img: "valorant_assets\/Hiko_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/hiko.png",
  },
  {
    name: "Dafran 准星",
    code: "0;P;c;1;h;0;0t;4;0o;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Dafran_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/dafran.png",
  },
  {
    name: "Mitch 准星",
    code: "0;P;c;5;o;1;f;0;0l;4;0o;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Mitch_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/mitch.png",
  },
  {
    name: "FNS 准星",
    code: "0;P;c;1;o;1;0l;3;0o;5;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/FNS_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/fns.png",
  },
  {
    name: "Myth 准星",
    code: "0;P;c;5;o;1;0l;3;0o;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Myth_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/myth.png",
  },
  {
    name: "Kiles 准星",
    code: "0;P;c;1;h;0;f;0;0t;1;0l;3;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Kiles_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/kiles.png",
  },
  {
    name: "Flexinja 准星",
    code: "0;P;c;4;h;0;0l;5;0o;4;0a;1;1t;3;1l;0;1o;14;1a;0.34",
    local_img: "valorant_assets\/Flexinja_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/flexinja.png",
  },
  {
    name: "Curry 准星",
    code: "0;P;c;1;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Curry_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/curry.png",
  },
  {
    name: "b0i 准星",
    code: "0;P;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/b0i_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/b0i.png",
  },
  {
    name: "Zellsis 准星",
    code: "0;P;c;4;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Zellsis_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/zellsis.png",
  },
  {
    name: "Lowel 准星",
    code: "0;P;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Lowel_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/lowel.png",
  },
  {
    name: "Keloqz 准星",
    code: "0;P;c;5;h;0;d;1;z;1;a;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Keloqz_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/keloqz.png",
  },
  {
    name: "Babybay 准星",
    code: "0;P;c;5;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1t;0;1l;0;1o;0;1a;0;1m;0;1f;0",
    local_img: "valorant_assets\/Babybay_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/babybay.png",
  },
  {
    name: "Kanpeki 准星",
    code: "0;P;c;5;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Kanpeki_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/kanpeki.png",
  },
  {
    name: "Doma 准星",
    code: "0;P;c;5;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Doma_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/doma.png",
  },
  {
    name: "Pyth 准星",
    code: "0;P;c;5;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Pyth_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/pyth.png",
  },
  {
    name: "Effys 准星",
    code: "0;P;c;1;h;0;f;0;0l;5;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Effys_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/effys.png",
  },
  {
    name: "pAura 准星",
    code: "0;P;h;0;0l;4;0o;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/pAura_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/paura.png",
  },
  {
    name: "crashies 准星",
    code: "0;P;c;1;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/crashies_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/crashies.png",
  },
  {
    name: "neT 准星",
    code: "0;P;c;1;h;0;m;1;0l;4;0o;2;0a;1;0f;0;1t;6;1l;0;1o;3;1a;0;1m;0;1f;0",
    local_img: "valorant_assets\/neT_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/net.png",
  },
  {
    name: "Mazino 准星",
    code: "0;P;c;1;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Mazino_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/mazino.png",
  },
  {
    name: "Xeta 准星",
    code: "0;P;c;1;o;1;f;0;0l;3;0o;5;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Xeta_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/xeta.png",
  },
  {
    name: "KRYPTIX 准星",
    code: "0;P;c;1;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/KRYPTIX_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/kryptix.png",
  },
  {
    name: "Cutler 准星",
    code: "0;P;c;5;h;0;0l;4;0o;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Cutler_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/cutler.png",
  },
  {
    name: "DavidP 准星",
    code: "0;P;c;4;h;0;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/DavidP_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/davidp.png",
  },
  {
    name: "Autimatic 准星",
    code: "0;P;c;1;h;0;0l;4;0o;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Autimatic_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/autimatic.png",
  },
  {
    name: "AZK 准星",
    code: "0;P;c;1;h;0;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/AZK_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/azk.png",
  },
  {
    name: "Shinobi 准星",
    code: "0;P;c;1;h;0;0l;4;0o;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Shinobi_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/shinobi.png",
  },
  {
    name: "Brax 准星",
    code: "0;P;c;1;h;0;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/Brax_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/brax.png",
  },
  {
    name: "DaZeD 准星",
    code: "0;P;c;1;h;0;0l;4;0a;1;0f;0;1b;0",
    local_img: "valorant_assets\/DaZeD_准星.png",
    img_url: "https:\/\/image.valdb.com\/teams\/dazed.png",
  },
];
